path = r'e:\MinQMT\F3_0614\BackTest\qixingaozhao_backtest_runner.py'
lines = [
"\n\ndef _write_excel(job, trades_df, rounds_df, per_sym_df, portfolio, params, text_summary):",
"    from .backtest_strategy_report_excel import _excel_scalar, _excel_stringify_float_columns",
"    from InnerStrategy.inner_registry import get_strategy_entry",
"    from datetime import datetime as _dt",
"    ts = _dt.now().strftime('%Y%m%d_%H%M%S')",
"    path = _reports_dir() / ('strategy_backtest_%s_%s.xlsx' % (job.strategy_key, ts))",
"    se = get_strategy_entry(job.strategy_key) or {}",
"    strat_row = pd.DataFrame([{'strategy_key': job.strategy_key,",
"        'module': se.get('module', 'qixingaozhao_etf_rotation_strategy'),",
"        'class': se.get('class', 'QixingaozhaoEtfRotationStrategy'),",
"        'label': se.get('label', '')}])",
"    job_rows = pd.DataFrame([",
"        ('initial_capital', job.initial_capital), ('start_date', job.start_date),",
"        ('end_date', job.end_date), ('strategy_key', job.strategy_key),",
"        ('backtest_mode', job.backtest_mode)], columns=['key', 'value'])",
"    params_df = pd.DataFrame([{'key': k, 'value': _excel_scalar(v)} for k, v in sorted(params.items())])",
"    port_df = pd.DataFrame([{'key': k, 'value': _excel_scalar(v)} for k, v in sorted(portfolio.items())])",
"    dom_count = len(FULL_ETF_POOL) - len(OVERSEAS_ETF_POOL) - len(COMMODITY_ETF_POOL)",
"    etf_pool_df = pd.DataFrame({",
"        'category': (['海外ETF'] * len(OVERSEAS_ETF_POOL)",
"                     + ['商品ETF'] * len(COMMODITY_ETF_POOL)",
"                     + ['A股ETF'] * dom_count),",
"        'code': FULL_ETF_POOL})",
"    td = _excel_stringify_float_columns(trades_df.copy()) if not trades_df.empty else trades_df",
"    rt = _excel_stringify_float_columns(rounds_df.copy()) if not rounds_df.empty else rounds_df",
"    ps = _excel_stringify_float_columns(per_sym_df.copy()) if not per_sym_df.empty else per_sym_df",
"    if not td.empty and 'datetime' in td.columns:",
"        td = td.sort_values('datetime', kind='mergesort').reset_index(drop=True)",
"    if not rt.empty and 'open_datetime' in rt.columns:",
"        rt = rt.sort_values('open_datetime', kind='mergesort').reset_index(drop=True)",
"    text_lines = text_summary.splitlines()",
"    text_df = pd.DataFrame({'line_no': range(1, len(text_lines) + 1), 'content': text_lines})",
"    with pd.ExcelWriter(path, engine='openpyxl') as writer:",
"        job_rows.to_excel(writer, sheet_name='回测任务', index=False)",
"        strat_row.to_excel(writer, sheet_name='策略注册', index=False)",
"        params_df.to_excel(writer, sheet_name='策略参数', index=False)",
"        port_df.to_excel(writer, sheet_name='组合收益统计', index=False)",
"        etf_pool_df.to_excel(writer, sheet_name='ETF池', index=False)",
"        td.to_excel(writer, sheet_name='逐笔买卖明细', index=False)",
"        rt.to_excel(writer, sheet_name='开平回合盈亏', index=False)",
"        ps.to_excel(writer, sheet_name='按ETF汇总统计', index=False)",
"        text_df.to_excel(writer, sheet_name='文本报告', index=False)",
"    return path.resolve()",
"\n\ndef run_qixingaozhao_backtest(job, *, progress=None):",
"    _log(progress, '========== 七星高照ETF轮动 向量回测 开始 ==========')",
"    strategy = QixingaozhaoEtfRotationStrategy()",
"    p = strategy.params",
"    all_codes = list(set(FULL_ETF_POOL + list(REGIME_INDEXES.values()) + [DEFENSIVE_ETF]))",
"    try:",
"        df = _fetch_panel(all_codes, job.start_date, job.end_date, progress)",
"    except Exception as exc:",
"        msg = '行情面板拉取失败: %s' % exc",
"        _log(progress, '[ERROR] ' + msg)",
"        return BacktestResult(False, msg)",
"    if df.empty:",
"        return BacktestResult(False, '行情面板为空，无法回测。')",
"    index_codes = set(REGIME_INDEXES.values())",
"    etf_data = _panel_to_daily_dict(",
"        df[~df['vt_symbol'].isin(index_codes)],",
"        [c for c in all_codes if c not in index_codes])",
"    index_data = _panel_to_daily_dict(",
"        df[df['vt_symbol'].isin(index_codes)], list(index_codes))",
"    start_ts = pd.Timestamp('%s-%s-%s' % (job.start_date[:4], job.start_date[4:6], job.start_date[6:8]))",
"    end_ts = pd.Timestamp('%s-%s-%s' % (job.end_date[:4], job.end_date[4:6], job.end_date[6:8]))",
"    all_dates = sorted(set(pd.Timestamp(dt).normalize() for dt in df['datetime']))",
"    trade_dates = [d for d in all_dates if start_ts <= d <= end_ts]",
"    if not trade_dates:",
"        return BacktestResult(False, '回测区间内无有效交易日，请扩大日期范围或检查数据。')",
"    _log(progress, '  回测交易日数：%d，起止：%s~%s' % (",
"        len(trade_dates), str(trade_dates[0].date()), str(trade_dates[-1].date())))",
"    trades_df, rounds_df, per_sym_df, portfolio = _run_daily_simulation(",
"        strategy, etf_data, index_data, trade_dates, job.initial_capital, progress)",
"    n_round = portfolio['total_round_trips']",
"    total_pnl = portfolio['total_realized_pnl_cash']",
"    ret = portfolio['simple_return_vs_initial_capital']",
"    win_rate = portfolio['all_round_trips_win_rate']",
"    ret_str = ('%.2f%%' % (ret * 100)) if math.isfinite(ret) else 'N/A'",
"    wr_str = ('%.1f%%' % (win_rate * 100)) if math.isfinite(win_rate) else 'N/A'",
"    text_lines = [",
"        '七星高照 ETF 轮动超级增强 - 向量回测报告',",
"        '回测区间: %s ~ %s' % (job.start_date, job.end_date),",
"        '初始资金: %.2f' % job.initial_capital,",
"        '动量回看: %d日  持仓数: %d只' % (p['lookback_days'], p['holdings_num']),",
"        '防御ETF: ' + DEFENSIVE_ETF, '',",
"        '完整开平回合数: %d' % n_round,",
"        '总已实现盈亏(元): %.2f' % total_pnl,",
"        '简单收益率(盈亏/初始资金): ' + ret_str,",
"        '胜率: ' + wr_str, '',",
"        '策略参数:',",
"    ] + ['  %s: %s' % (k, v) for k, v in sorted(p.items())]",
"    text_summary = '\\n'.join(text_lines)",
"    _log(progress, text_summary)",
"    try:",
"        excel_path = _write_excel(job, trades_df, rounds_df, per_sym_df, portfolio, p, text_summary)",
"        _log(progress, '  Excel 报告已写入: ' + str(excel_path))",
"    except Exception as exc:",
"        _log(progress, '  [WARN] Excel 写入失败: ' + str(exc))",
"        excel_path = None",
"    _log(progress, '========== 七星高照ETF轮动 向量回测 完成 ==========')",
"    return BacktestResult(ok=True, message=text_summary,",
"                          excel_path=str(excel_path) if excel_path else None)",
]
with open(path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('excel+entry appended, lines=%d' % len(lines))
