path = r'e:\MinQMT\F3_0614\BackTest\qixingaozhao_backtest_runner.py'
lines = [
"\n\ndef _run_daily_simulation(strategy, etf_data, index_data, trade_dates, initial_capital, progress):",
"    p = strategy.params",
"    lookback = int(p['lookback_days'])",
"    regime_ma = int(p.get('weak_period_ma_lookback', 10))",
"    weak_max_days = int(p.get('weak_period_max_days', 20))",
"    profit_prot = bool(p.get('enable_profit_protection', True))",
"    profit_lookback = int(p.get('profit_protection_lookback', 1))",
"    profit_threshold = float(p.get('profit_protection_threshold', 0.05))",
"    is_weak = False",
"    weak_counter = 0",
"    positions = {}",
"    all_trades = []",
"    all_rounds = []",
"    LOT = 100",
"    total_days = len(trade_dates)",
"    for day_idx, date_key in enumerate(trade_dates):",
"        if day_idx % 60 == 0:",
"            pct = int(day_idx * 100 / total_days) if total_days else 0",
"            _log(progress, '  [%d/%d %d%%] %s ...' % (day_idx, total_days, pct, str(date_key.date())))",
"        if p.get('enable_regime_switch', True):",
"            idx_closes = {}",
"            for _code in REGIME_INDEXES.values():",
"                _d = index_data.get(_code)",
"                if _d is None:",
"                    continue",
"                sel = [float(c) for dt, c in zip(_d['dates'], _d['closes'])",
"                       if pd.Timestamp(dt).normalize() <= date_key]",
"                if sel:",
"                    idx_closes[_code] = sel",
"            newly_weak = regime_is_weak(idx_closes, ma_lookback=regime_ma)",
"            if not is_weak:",
"                if newly_weak:",
"                    is_weak = True",
"                    weak_counter = 0",
"            else:",
"                weak_counter += 1",
"                above = sum(",
"                    1 for _c, _cl in idx_closes.items()",
"                    if len(_cl) >= regime_ma and _cl[-1] >= _mean_values(_cl[-regime_ma:]))",
"                if above >= 3 or weak_counter >= weak_max_days:",
"                    is_weak = False",
"                    weak_counter = 0",
"        active_pool = strategy.get_active_pool(is_weak)",
"        all_candidates = list(set(active_pool + [DEFENSIVE_ETF]))",
"        closes_by_etf = {}",
"        volumes_by_etf = {}",
"        today_prices = {}",
"        today_vols = {}",
"        for code in all_candidates:",
"            d = etf_data.get(code)",
"            if d is None:",
"                continue",
"            hist_c = [float(c) for dt, c in zip(d['dates'], d['closes'])",
"                      if pd.Timestamp(dt).normalize() < date_key]",
"            hist_v = [float(v) for dt, v in zip(d['dates'], d['volumes'])",
"                      if pd.Timestamp(dt).normalize() < date_key]",
"            today_c = _get_close_on(d, date_key)",
"            if today_c is None or today_c <= 0:",
"                continue",
"            if len(hist_c) < lookback:",
"                continue",
"            closes_by_etf[code] = hist_c",
"            volumes_by_etf[code] = hist_v",
"            today_prices[code] = today_c",
"            today_vols[code] = sum(float(v) for dt, v in zip(d['dates'], d['volumes'])",
"                                   if pd.Timestamp(dt).normalize() == date_key)",
"        protected_sells = set()",
"        if profit_prot:",
"            for code, (entry_price, _edt, _sh) in list(positions.items()):",
"                d = etf_data.get(code)",
"                if d is None:",
"                    continue",
"                cp = _get_close_on(d, date_key)",
"                if cp is None:",
"                    continue",
"                recent = [float(c) for dt, c in zip(d['dates'], d['closes'])",
"                          if pd.Timestamp(dt).normalize() < date_key]",
"                if len(recent) < profit_lookback:",
"                    continue",
"                max_h = max(recent[-profit_lookback:])",
"                if max_h > 0 and cp <= max_h * (1.0 - profit_threshold):",
"                    protected_sells.add(code)",
"        _, target_codes = strategy.select_targets(",
"            active_pool, closes_by_etf, volumes_by_etf, today_prices, today_vols)",
"        target_codes = [c for c in target_codes if c not in protected_sells]",
"        if not target_codes and DEFENSIVE_ETF in today_prices:",
"            target_codes = [DEFENSIVE_ETF]",
"        target_set = set(target_codes)",
"        to_sell = (set(positions.keys()) - target_set) | (set(positions.keys()) & protected_sells)",
"        for code in list(to_sell):",
"            if code not in positions:",
"                continue",
"            entry_price, entry_dt, shares = positions.pop(code)",
"            d = etf_data.get(code)",
"            sell_price = (_get_close_on(d, date_key) if d else None) or entry_price",
"            pnl_cash = (sell_price - entry_price) * shares",
"            pnl_pct = (sell_price / entry_price - 1.0) if entry_price > 0 else float('nan')",
"            all_trades.append({'vt_symbol': code, 'datetime': date_key, 'action': 'sell',",
"                'price': sell_price, 'volume': shares, 'open_datetime': entry_dt,",
"                'open_price': entry_price, 'round_pnl_pct': pnl_pct, 'round_pnl_cash': pnl_cash,",
"                'is_regime_weak': is_weak, 'profit_protected': code in protected_sells})",
"            all_rounds.append({'vt_symbol': code, 'open_datetime': entry_dt,",
"                'open_price': entry_price, 'close_datetime': date_key,",
"                'close_price': sell_price, 'volume': shares,",
"                'hold_calendar_days': _calendar_days(entry_dt, date_key),",
"                'round_pnl_pct': pnl_pct, 'round_pnl_cash': pnl_cash,",
"                'win': bool(math.isfinite(pnl_pct) and pnl_pct > 0)})",
"        for code in list(target_set - set(positions.keys())):",
"            if code not in today_prices:",
"                continue",
"            buy_price = today_prices[code]",
"            positions[code] = (buy_price, date_key, LOT)",
"            all_trades.append({'vt_symbol': code, 'datetime': date_key, 'action': 'buy',",
"                'price': buy_price, 'volume': LOT,",
"                'is_regime_weak': is_weak, 'profit_protected': False})",
"    trades_df = pd.DataFrame(all_trades) if all_trades else pd.DataFrame()",
"    rounds_df = pd.DataFrame(all_rounds) if all_rounds else pd.DataFrame()",
"    if not rounds_df.empty:",
"        per_sym = (rounds_df.groupby('vt_symbol', sort=False)",
"            .agg(n_round_trips=('round_pnl_cash', 'count'),",
"                 sum_round_pnl_cash=('round_pnl_cash', 'sum'),",
"                 mean_round_pnl_pct=('round_pnl_pct', 'mean'),",
"                 win_rounds=('win', 'sum')).reset_index())",
"        per_sym['win_rate'] = per_sym['win_rounds'] / per_sym['n_round_trips'].clip(lower=1)",
"    else:",
"        per_sym = pd.DataFrame()",
"    n_round = len(rounds_df)",
"    total_pnl = float(rounds_df['round_pnl_cash'].sum()) if n_round else 0.0",
"    cap = float(initial_capital) if initial_capital > 0 else float('nan')",
"    ret = total_pnl / cap if cap > 0 else float('nan')",
"    wins = int(rounds_df['win'].sum()) if n_round and 'win' in rounds_df.columns else 0",
"    win_rate = wins / n_round if n_round else float('nan')",
"    mean_pnl = float(rounds_df['round_pnl_pct'].mean()) if n_round else float('nan')",
"    portfolio = {",
"        'strategy': 'QixingaozhaoEtfRotationStrategy',",
"        'initial_capital_ui': cap, 'total_round_trips': n_round,",
"        'total_realized_pnl_cash': total_pnl, 'simple_return_vs_initial_capital': ret,",
"        'all_round_trips_win_rate': win_rate, 'all_round_trips_mean_pnl_pct': mean_pnl,",
"        'lookback_days': p['lookback_days'], 'holdings_num': p['holdings_num'],",
"        'enable_regime_switch': p['enable_regime_switch'],",
"        'enable_avoid_a_share': p['enable_avoid_a_share'],",
"        'enable_volume_check': p['enable_volume_check'],",
"        'enable_profit_protection': p['enable_profit_protection'],",
"        'note': 'Daily close-price rebalancing. No fees/slippage. Score=annualized_ret*R2.',",
"    }",
"    return trades_df, rounds_df, per_sym, portfolio",
]
with open(path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('sim appended, lines=%d' % len(lines))
